### ISSUE TITLE
TypeScript type declaration file

### ISSUE THREAD

**Issue by geopic** [nodef/extra-array#1]
If you want I can write a TypeScript type declaration file for this package so that TS developers can utilise the type-checking feature of the language as they use this package. Let me know if you are interested.

**Comment by wolfram77** [comment]
Could you wait for about a week, while i update some packages, including this one? I am thinking of Haskell-like `Data.List`, and feel like an update is a good way to go. (I learnt Haskell last semester in POPL course).

Thank you for your interest. If you are interested could you instead help with https://github.com/nodef/extra-boolean, which i have finished updating and added wikis (=> api stable). It also has a subpackage generator for people using Webpack to be able to include specific functions.

**Comment by geopic** [comment]
Sure I'll check out the other package now @wolfram77.

**Comment by wolfram77** [comment]
@geopic Would you like to add declaration file now? I just finished this. Now i need to go around, find some more work for myself and keep myself busy. My institute is now closed.

**Comment by geopic** [comment]
Sure thing @wolfram77 , I'll start on it now.
